version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.16
jobs:
  shellspec:
    docker:
     - image: cimg/base:stable
    steps:
      - run: curl -fsSL https://git.io/shellspec | sh -s -- -y
      - run: sudo ln -s ${HOME}/.local/lib/shellspec/shellspec /usr/local/bin/shellspec
      - run: sudo apt update -y
      - run: sudo apt install -y kcov
      - run: shellspec --kcov

workflows:
  codequality:
    jobs:
      - shellcheck/check:
          exclude: ./git/*
      - shellspec
